version: "3.3"
services: 
  db:
    image: postgres:12.10
    expose:
      - 5400
    ports:
      - 5400:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rodoviariadb